### ISSUE TITLE
Runtime Error with secondary model off

### ISSUE THREAD

**Issue by DillFrescott** [jina-ai/discoart#120]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-3-9112366ef044>](https://localhost:8080/#) in <module>()
      5     n_batches=1,
      6     use_secondary_model=False,
----> 7     steps=250,
      8 )

19 frames
[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in _conv_forward(self, input, weight, bias)
    452                             _pair(0), self.dilation, self.groups)
    453         return F.conv2d(input, weight, bias, self.stride,
--> 454                         self.padding, self.dilation, self.groups)
    455 
    456     def forward(self, input: Tensor) -> Tensor:

RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

**Comment by hanxiao** [comment]
1. what is your VRAM?
2. `use_secondary_model=False` use more memory than `use_secondary_model=True` (that's why it is default)

this is the result on default `create()`  on 0.10.4 , so less than 12GB

![image](https://user-images.githubusercontent.com/2041322/182098647-94555b3c-9b90-4591-905a-053df2ba8125.png)

and this is when secondary model is off, <20GB

```python
from discoart import create

create(use_secondary_model=False)
```

![image](https://user-images.githubusercontent.com/2041322/182098743-e859a056-c874-40b0-a54d-cc2e514b0db7.png)

**Comment by DillFrescott** [comment]
Vram is 16 GB. Maybe thats why. Thank you for the info!
