### ISSUE TITLE
steps=250, the last two pictures(14, 15) is black

### ISSUE THREAD

**Issue by Juliaququ** [jina-ai/discoart#20]
steps=250, the last two pictures(14, 15) is black. 
And can not download
ERROR - failed to download https://v-diffusion.s3.us-west-2.amazonaws.com/secondary_model_imagenet_2.pth

**Comment by hanxiao** [comment]
> steps=250, the last two pictures(14, 15) is black.

yes, because you dont have enough pictures. imagine you run 10 steps and each step gives your 1 picture so you have 10 pictures and now you draw 10 pictures in a 4x4 grid that has total 16 slots. what would be the last 6 slots? 

answer: black

> ERROR - failed to download https://v-diffusion.s3.us-west-2.amazonaws.com/secondary_model_imagenet_2.pth

should not affect anything, if so, please update to DiscoArt 0.3

**Comment by Juliaququ** [comment]
> > steps=250, the last two pictures(14, 15) is black.
> 
> yes, because you dont have enough pictures. imagine you run 10 steps and each step gives your 1 picture so you have 10 pictures and now you draw 10 pictures in a 4x4 grid that has total 16 slots. what would be the last 6 slots?
> 
> answer: black
> 
> > ERROR - failed to download https://v-diffusion.s3.us-west-2.amazonaws.com/secondary_model_imagenet_2.pth
> 
> should not affect anything, if so, please update to DiscoArt 0.3

Thanks a lot!
